/*
 * Kaartje.java
 *
 * Created on February 16, 2006, 2:53 PM
 */
package com.vectorprint.client;

import java.awt.Color;
import java.io.IOException;
import java.util.Scanner;

/**
 * Een kaartje voor op het planbord waarin een tekst kan worden gezet en met kleur een status kan worden aangegeven. De
 * celinhoud van het datamodel bestaat uit kaartjes, om dit goed te ondersteunen in swings JTable is er een aparte
 * renderer nodig voor een kaartje.
 *
 * @author Eduard Drenth at VectorPrint.nl
 */
public class Kaartje extends javax.swing.JPanel implements Cloneable {

   /**
    * Creates new form Kaartje
    */
   public Kaartje() {
      initComponents();
   }

   /**
    * Zorg ervoor dat een kaartje als een string verstuurd kan worden. Niet perse nodig, want de superclass is al
    * Serializable, wel een flinke optimalisatie omdat we met minimale state een kaartje kunnen opbouwen.
    *
    * @param out
    * @throws IOException
    */
   private void writeObject(java.io.ObjectOutputStream out)
       throws IOException {
      out.writeObject(new StringBuffer(30)
          .append(naaien.getBackground().hashCode()).append("\t")
          .append(omslagbinnen.getBackground().hashCode()).append("\t")
          .append(tekst.getText()).toString());
   }

   /**
    * Bouw een geserializeerd kaartje opnieuw op aan de ontvangende kant.
    *
    * @param in
    * @throws IOException
    * @throws ClassNotFoundException
    */
   private void readObject(java.io.ObjectInputStream in)
       throws IOException, ClassNotFoundException {
      initComponents();
      Scanner sc = new Scanner(in.readObject().toString()).useDelimiter("\t");
      int i = 0;
      klaar:
      while (sc.hasNext()) {
         switch (i) {
            case 0:
               naaien.setBackground(new Color(sc.nextInt()));
               break;
            case 1:
               omslagbinnen.setBackground(new Color(sc.nextInt()));
               break;
            case 2:
               tekst.setText(sc.next());
               break klaar;
         }
         i++;
      }
   }

   /**
    * maak een kopie van een kaartje
    *
    * @return
    */
   public Object clone() {
      Kaartje k = new Kaartje();
      k.tekst.setText(tekst.getText());
      k.naaien.setBackground(naaien.getBackground());
      k.omslagbinnen.setBackground(omslagbinnen.getBackground());
      return k;
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
    * content of this method is always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      tekst = new javax.swing.JLabel();
      naaien = new javax.swing.JLabel();
      omslagbinnen = new javax.swing.JLabel();

      setBackground(new java.awt.Color(255, 255, 255));
      setBorder(javax.swing.BorderFactory.createEtchedBorder());
      setMaximumSize(new java.awt.Dimension(70, 40));
      setMinimumSize(new java.awt.Dimension(70, 40));
      setPreferredSize(new java.awt.Dimension(70, 40));
      setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      tekst.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
      tekst.setForeground(new java.awt.Color(255, 11, 11));
      tekst.setAutoscrolls(true);
      add(tekst, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 18, 60, 15));

      naaien.setBackground(new java.awt.Color(153, 153, 153));
      naaien.setToolTipText("Klik om naaien aan/uit te zetten");
      naaien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      naaien.setOpaque(true);
      add(naaien, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 60, 6));

      omslagbinnen.setBackground(new java.awt.Color(102, 102, 102));
      omslagbinnen.setToolTipText("Klik om omslagbinnen aan/uit te zetten");
      omslagbinnen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      omslagbinnen.setOpaque(true);
      add(omslagbinnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 11, 60, 6));
   }// </editor-fold>//GEN-END:initComponents
   // Variables declaration - do not modify//GEN-BEGIN:variables
   public javax.swing.JLabel naaien;
   public javax.swing.JLabel omslagbinnen;
   public javax.swing.JLabel tekst;
   // End of variables declaration//GEN-END:variables
}
