/*
 * Kaartje.java
 *
 * Created on February 16, 2006, 2:53 PM
 */
package com.vectorprint.dragdropedit;

import java.awt.Color;

/**
 * ondersteuning voor inline editting van Kaartjes
 *
 * @author Eduard Drenth at VectorPrint.nl
 */
public class EdittableKaartje extends javax.swing.JPanel {

   /**
    * color to use for the state naaien
    */
   public static final Color naaikleur = Color.YELLOW;
   /**
    * color to use for the state omslag binnen
    */
   public static final Color omslagkleur = Color.GREEN;

   public EdittableKaartje() {
      initComponents();
   }

   void toggleNaaiKleur() {
      naaien.setBackground((naaien.getBackground().equals(naaikleur)) ? Color.GRAY : naaikleur);
   }

   void toggleOmslagKleur() {
      omslagbinnen.setBackground((omslagbinnen.getBackground().equals(omslagkleur)) ? Color.DARK_GRAY : omslagkleur);
   }

   void setFocusOnTekst() {
      if (!tekst.isFocusOwner()) {
         tekst.requestFocusInWindow();
         tekst.selectAll();
      }
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
    * content of this method is always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      naaien = new javax.swing.JLabel();
      omslagbinnen = new javax.swing.JLabel();
      tekst = new javax.swing.JTextField();

      setBackground(new java.awt.Color(204, 255, 204));
      setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 0), new java.awt.Color(0, 102, 0)));
      setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

      naaien.setBackground(new java.awt.Color(153, 153, 153));
      naaien.setToolTipText("Klik om naaien aan/uit te zetten");
      naaien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      naaien.setOpaque(true);
      naaien.setRequestFocusEnabled(false);
      naaien.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            toggleNaaiKleur(evt);
         }
      });
      add(naaien, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 60, 6));

      omslagbinnen.setBackground(new java.awt.Color(102, 102, 102));
      omslagbinnen.setToolTipText("Klik om omslagbinnen aan/uit te zetten");
      omslagbinnen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      omslagbinnen.setOpaque(true);
      omslagbinnen.setRequestFocusEnabled(false);
      omslagbinnen.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            toggleOmslagKleur(evt);
         }
      });
      add(omslagbinnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 11, 60, 6));

      tekst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      tekst.setDragEnabled(true);
      tekst.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
         public void propertyChange(java.beans.PropertyChangeEvent evt) {
            tekstPropertyChange(evt);
         }
      });
      add(tekst, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 17, 60, 19));
   }// </editor-fold>//GEN-END:initComponents

    private void tekstPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tekstPropertyChange
       if (evt.getPropertyName().equals("ancestor")) {
          setFocusOnTekst();
       }
    }//GEN-LAST:event_tekstPropertyChange

    private void toggleOmslagKleur(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleOmslagKleur
       toggleOmslagKleur();
    }//GEN-LAST:event_toggleOmslagKleur

    private void toggleNaaiKleur(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleNaaiKleur
       toggleNaaiKleur();
    }//GEN-LAST:event_toggleNaaiKleur
   // Variables declaration - do not modify//GEN-BEGIN:variables
   javax.swing.JLabel naaien;
   javax.swing.JLabel omslagbinnen;
   javax.swing.JTextField tekst;
   // End of variables declaration//GEN-END:variables
}
;